# Generated by Django 3.2.15 on 2022-09-30 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchKunn', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
