# Generated by Django 3.2.15 on 2022-09-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchKunn', '0002_rename_books_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '本', 'verbose_name_plural': '本'},
        ),
        migrations.AlterField(
            model_name='book',
            name='Author',
            field=models.CharField(max_length=50, verbose_name='著者'),
        ),
        migrations.AlterField(
            model_name='book',
            name='Category',
            field=models.CharField(max_length=50, verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='book',
            name='Title',
            field=models.CharField(max_length=100, verbose_name='タイトル'),
        ),
    ]
