# Generated by Django 3.2.15 on 2022-09-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchKunn', '0003_auto_20220930_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Registration_date',
            field=models.DateField(verbose_name='登録日'),
        ),
    ]
