# Generated by Django 3.2.15 on 2022-09-30 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchKunn', '0004_alter_book_registration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Registration_date',
            new_name='registration_date',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Title',
            new_name='title',
        ),
    ]
