# Generated by Django 3.2.15 on 2022-09-30 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchKunn', '0005_auto_20220930_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='category',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='registration_date',
            new_name='Registration_date',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='Title',
        ),
    ]
